### ISSUE TITLE
Cannot see any data in the web app

### ISSUE THREAD

**Issue by navjeetc** [Senzing/senzing-up#34] opened 2021-02-02 02:04 UTC
**Describe the bug**
So I am starting the process again to test senzing after a gap and having issues. After I run _~/senzing-up.sh ~/senzing-up-demonstration_, the web app is accessible but searching for any data returns 500 error in developer console.

**To Reproduce**
1.
```
curl -X GET \
      --output ~/senzing-up.sh \
      https://raw.githubusercontent.com/Senzing/senzing-up/master/senzing-up.sh
```
followed by    `chmod +x ~/senzing-up.sh`

2. Run `~/senzing-up.sh ~/senzing-up-demonstration` (I renamed my previous senzing-up-demonstration dir first)
3. Towards the end of previous command I see this output:
```
2021-02-01 02:34:42,895 senzing-50070155I /etc/opt/senzing/g2config.json - Deleting
2021-02-01 02:34:42,898 senzing-50070298I Exit {"data_dir": "/opt/senzing/data", "db2dsdriver_cfg_contents": null, "debug": false, "delay_in_seconds": 0, "elapsed_time": 1.536212682723999, "enable_db2": false, "enable_mssql": false, "enable_mysql": false, "enable_postgresql": false, "engine_configuration_json": null, "etc_dir": "/etc/opt/senzing", "g2_dir": "/opt/senzing/g2", "gid": 1001, "governor_url": "https://raw.githubusercontent.com/Senzing/governor-postgresql-transaction-id/master/senzing_governor.py", "license_base64_encoded": null, "mssql_odbc_ini_contents": null, "program_updated": "2020-11-28", "program_version": "1.6.3", "sleep_time_in_seconds": 0, "start_time": 1612146881.361669, "stop_time": 1612146882.8978817, "subcommand": "initialize", "uid": 1001, "update_ini_files": false, "var_dir": "/var/opt/senzing"}
Loading sample data.
2021-02-01 02:34:44.497 [pyG2Diagnostic:139863845091136] CRIT: Unable to load transliteration rule :${SENZING_DATA_DIR}/anyTransRule.ibm

ERROR: Could not start the G2 engine for check_resources()
       7317E|Failed to open file: ${SENZING_DATA_DIR}/cfgVariant.json
 Sun Jan 31 21:34:44 EST 2021 Installation is complete.
== Installation is complete.
==============================================================================
== entity-search-web-app running on http://192.168.86.31:8251
== senzing-api-server running on http://192.168.86.31:8250/heartbeat
== Mount information: (Format: in container > on host)
==   /etc/opt/senzing  > /Users/navjeetc/senzing-up-demonstration/docker-etc
==   /opt/senzing/data > /Users/navjeetc/senzing-up-demonstration/data
==   /opt/senzing/g2   > /Users/navjeetc/senzing-up-demonstration/g2
==   /var/opt/senzing  > /Users/navjeetc/senzing-up-demonstration/var
== Logs:
==   /Users/navjeetc/senzing-up-demonstration/var/log/senzing-webapp-demo.log.log
==   and/or run 'docker logs senzing-web-app-demo'
== For more information:
== http://hub.senzing.com/senzing-environment/reference#senzing-webapp-demo
==============================================================================
== Project location: /Users/navjeetc/senzing-up-demonstration
==
== To stop docker formation, run:
== /Users/navjeetc/senzing-up-demonstration/docker-bin/senzing-webapp-demo.sh down
==
== To restart docker formation, run:
== /Users/navjeetc/senzing-up-demonstration/docker-bin/senzing-webapp-demo.sh up
==
== For more information, see:
== https://senzing.github.io/senzing-up
==============================================================================
Sun Jan 31 21:34:49 EST 2021 Done.
```
4. At this point web app is up and running but I put "Bobby Jones" in search box I see error 500 in browser console. Looks like data may not be loaded

**Expected behavior**
I should see Bobby _Jones_ data in results

**Desktop (please complete the following information):**

- OS: MacOS-Catalina

**Additional context**
I was able to do all this about a moth ago with your help. I did have resource allocation issue at that time.
Also when I run command: /_G2Loader.py -P -p demo/sample/project.json_

I get this output

```
ERROR: G2Module.ini is missing from the search path location(s). Searched:
/Users/navjeetc/senzing-up-demonstration/g2-2.3.1/python
/opt/senzing/etc

Traceback (most recent call last):
  File "./G2Loader.py", line 1359, in <module>
    iniFileName = pathlib.Path(G2Paths.get_G2Module_ini_path()) if not args.iniFile else pathlib.Path(args.iniFile[0]).resolve()
  File "/Users/navjeetc/senzing-up-demonstration/g2-2.3.1/python/G2Paths.py", line 40, in get_G2Module_ini_path
    return __get_file_path('G2Module.ini')
  File "/Users/navjeetc/senzing-up-demonstration/g2-2.3.1/python/G2Paths.py", line 76, in __get_file_path
    raise FileNotFoundError(f'[Errno {errno.ENOENT}] {os.strerror(errno.ENOENT)}: {filename} - {msg_args}')
FileNotFoundError: [Errno 2] No such file or directory: G2Module.ini - Use command line argument -c (--inifile) to specify the path & filename for G2Module.ini.

```

**Comment by docktermj** [comment] 2021-02-03 15:41
Hi @navjeetc!

I am able to reproduce the error on my Mac and will be working on this today.

**Comment by docktermj** [comment] 2021-02-03 16:07
I tested on Linux.  Same problem.   

### Developer Notes:

Since I know I tested on Linux for senzing-up 1.2.1,  I'm suspecting something changed "beneath" the code.

**Comment by docktermj** [comment] 2021-02-03 19:12
### Developer Notes:

The  issue seems to be that the `docker-etc/G2Module.ini` file isn't being crafted correctly.   Investigating that now.

**Comment by docktermj** [comment] 2021-02-03 19:32
Root issue in a different repository.   New issue created:  https://github.com/Senzing/docker-init-container/issues/104

**Comment by docktermj** [comment] 2021-02-03 19:33
I'll use this issue to make `senzing-up.sh` more resilient to this type of issue.

**Comment by navjeetc** [comment] 2021-02-04 17:27
I saw some changes committed to Senzing/docker-init-container. Has that resolved this issue?

**Comment by docktermj** [comment] 2021-02-04 20:12
@navjeetc Doing testing now.   Linux tested fine,  Mac is next.

**Comment by docktermj** [comment] 2021-02-04 22:31
@navjeetc Having issues with Mac.  Still investigating.

**Comment by docktermj** [comment] 2021-02-05 14:51
@navjeetc Here's where I'm at:

1. Everything works fine in Linux.
1. On Mac,  the system comes up without error, but the "truth set" data isn't loaded into the SQLite database.

So I'm still investigating.

**Comment by navjeetc** [comment] 2021-02-05 17:59
@docktermj Thanks for the update. I really need it working on Mac as that is our development platform.

**Comment by docktermj** [comment] 2021-02-05 20:44
@navjeetc I'm having a dickens of a time testing on Mac.  I'm wondering if I just don't have enough memory.   Everything is coming up, but the data from the "truth set" isn't being loaded. 

What I've done is pull the changes into the "master" branch.  Please download a new copy of `senzing-up.sh` and try it on your Mac to see if you get better results.   Let me know what you see.

In the meantime, I'll try to see if I can figure out what's going on in my Mac.

**Comment by docktermj** [comment] 2021-02-05 20:56
@navjeetc Just to keep you up-to-date.  I upped my Docker Desktop memory to 5 GB and I got a glimmer of hope.   Will be re-running full test to see if it was just an issue with my Mac's Docker Desktop settings.

**Comment by docktermj** [comment] 2021-02-05 21:20
@navjeetc That was the problem, my Mac didn't have enough Memory allocated to Docker Desktop.  

Ok, so everything you need should be in the master branch.  Go ahead and try again.

If it doesn't work, let me know.  If it does work, just go ahead and close this issue.

**Comment by navjeetc** [comment] 2021-02-06 20:43
I ran step 1 and 2 mentioned above but still having same issue. Search for "Bobby Jones" still returns 500 error.
Here is last few last lines output after running step 2.

```
2021-02-06 15:34:10,893 senzing-50150165I /Users/navjeetc/senzing-up-demonstration/docker-bin/senzing-yum.sh - Creating file
2021-02-06 15:34:10,894 senzing-50150165I /Users/navjeetc/senzing-up-demonstration/docker-bin/swagger-ui.sh - Creating file
2021-02-06 15:34:10,894 senzing-50150298I Exit {"debug": false, "docker_host_ip_addr": "192.168.86.31", "elapsed_time": 0.012233972549438477, "g2_database_url": "sqlite3://na:na@/var/opt/senzing/sqlite/G2C.db", "program_updated": "2021-01-14", "program_version": "1.2.3", "project_dir": "/Users/navjeetc/senzing-up-demonstration", "project_name": "senzing", "sleep_time_in_seconds": 0, "start_time": 1612643650.882447, "stop_time": 1612643650.894681, "subcommand": "add-docker-support-macos"}
Error response from daemon: network with name senzing-up already exists
Creating /Users/navjeetc/senzing-up-demonstration/docker-etc
Initializing Senzing configuration.
2021-02-06 20:34:12,005 senzing-50070297I Enter {"data_dir": "/opt/senzing/data", "db2dsdriver_cfg_contents": null, "debug": false, "delay_in_seconds": 0, "enable_db2": false, "enable_mssql": false, "enable_mysql": false, "enable_postgresql": false, "engine_configuration_json": null, "etc_dir": "/etc/opt/senzing", "g2_dir": "/opt/senzing/g2", "gid": 1001, "governor_url": "https://raw.githubusercontent.com/Senzing/governor-postgresql-transaction-id/master/senzing_governor.py", "license_base64_encoded": null, "mssql_odbc_ini_contents": null, "program_updated": "2020-11-28", "program_version": "1.6.3", "sleep_time_in_seconds": 0, "start_time": 1612643652.005828, "subcommand": "initialize", "uid": 1001, "update_ini_files": false, "var_dir": "/var/opt/senzing"}
Traceback (most recent call last):
  File "/app/init-container.py", line 1847, in <module>
    globals()[subcommand_function_name](args)
  File "/app/init-container.py", line 1623, in do_initialize
    change_module_ini(config)
  File "/app/init-container.py", line 1013, in change_module_ini
    old_database_url = config_parser.get('SQL', 'CONNECTION')
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'SQL'
Loading sample data.
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: mkdir /opt/senzing/g2/python: no such file or directory: unknown.
 Sat Feb  6 15:34:13 EST 2021 Installation is complete.
== Installation is complete.
==============================================================================
== entity-search-web-app running on http://192.168.86.31:8251
== senzing-api-server running on http://192.168.86.31:8250/heartbeat
```
Not sure if the message below is the problem:
"docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: mkdir /opt/senzing/g2/python: no such file or directory: unknown."

**Comment by navjeetc** [comment] 2021-02-06 21:07
Also senzing web app log has this error:

```
Error response from daemon: No such container: senzing-init-container
 28 Error: No such container: senzing-init-container
```

**Comment by docktermj** [comment] 2021-02-08 14:40
@navjeetc A few things to make sure you are starting cleanly:

1. Move your old version of `/Users/navjeetc/senzing-up-demonstration` to a backup directory name so that a new directory is created.
2. Run
```
sudo docker system prune --volumes
```
To clean up any old images and the `senzing-up` network`
3.  Run
```
sudo docker ps --all
```
to make sure all of the containers on the previous run are gone.
4. Get a new copy of `senzing-up.sh`

### Developers notes

1. The error seen above is from https://github.com/Senzing/docker-init-container/blob/c330a844d6ea3ee3e64edfc003309bcc81f8f028/init-container.py#L1013. So `init-container.py` was running even though there's a  messages saying `No such container:  senzing-init-container`   At the root of the issue is that the contents of  `/etc/opt/senzing/G2Module.ini` (as specified inside the container) or `<project-dir>/docker-etc/G2Module.ini` on the host doesn't contain `SQL` > `CONNECTION`

**Comment by navjeetc** [comment] 2021-02-08 15:38
Thanks @docktermj for the tips. That did work and I am able to search for truth sample data. Now on to loading my custom data, followed by calling your REST APIs from my Ruby on Rails Web app.

**Comment by docktermj** [comment] 2021-02-08 15:41
@navjeetc I'm delighted to hear that.   If you think this issue has been solved, please close the issue.   If there's anything else we can do to help, just let us know.

**Closed** 2021-02-08 15:50 UTC
Labels: waiting-for-customer
